<a href="https://colab.research.google.com/github/lisagamilton/python_for_data_analysis/blob/main/database_connection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.cloud import bigquery
from google.oauth2 import service_account
import pandas as pd

In [3]:
credentials = service_account.Credentials.from_service_account_file('/content/credentials.json')

In [4]:
project_id = 'my-project-26-01-2026'

In [5]:
client = bigquery.Client(credentials=credentials,project=project_id)

In [6]:
query_text = f"""SELECT * FROM `my-project-26-01-2026.dataset1.customers`
LIMIT 100;"""

In [7]:
query = client.query(query_text)

In [8]:
result_df = query.to_dataframe()
result_df

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,None,None,%male,10,None,<NA>,NaN,None,NaT,None
1,None,None,mal%e,10,None,<NA>,NaN,None,NaT,None
2,None,None,mal%e,10,None,<NA>,NaN,None,NaT,None
3,None,None,%male,10,None,<NA>,NaN,None,NaT,None
4,None,None,ma%le,20,None,<NA>,NaN,None,NaT,None
...,...,...,...,...,...,...,...,...,...,...
95,I263168,C896576,Male,18,Technology,3,3150.00,Cash,2021-01-30,Kanyon
96,I433968,C138682,Male,18,Technology,3,3150.00,Cash,2021-06-19,Mall of Istanbul
97,I323146,C249575,Female,18,Books,5,75.75,Cash,2022-01-18,Metropol AVM
98,I733004,C241572,Male,18,Books,5,75.75,Cash,2022-05-05,Viaport Outlet
99,I584453,C713965,Female,18,Books,5,75.75,Credit Card,2022-07-29,Mall of Istanbul

In [9]:
result_df = result_df[result_df['invoice_no'].notnull()]
result_df

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
8,I130454,C155210,Male,18,Technology,1,1050.00,Cash,2023-01-09,Metropol AVM
9,I125572,C334714,Male,18,Technology,1,1050.00,Cash,2021-07-07,Forum Istanbul
10,I100911,C330379,Female,18,Technology,1,1050.00,Credit Card,2021-08-29,Metrocity
11,I139376,C115765,Male,18,Technology,1,1050.00,Cash,2022-03-11,Zorlu Center
12,I101070,C330130,Female,18,Technology,1,1050.00,Credit Card,2022-04-21,Kanyon
...,...,...,...,...,...,...,...,...,...,...
95,I263168,C896576,Male,18,Technology,3,3150.00,Cash,2021-01-30,Kanyon
96,I433968,C138682,Male,18,Technology,3,3150.00,Cash,2021-06-19,Mall of Istanbul
97,I323146,C249575,Female,18,Books,5,75.75,Cash,2022-01-18,Metropol AVM
98,I733004,C241572,Male,18,Books,5,75.75,Cash,2022-05-05,Viaport Outlet
99,I584453,C713965,Female,18,Books,5,75.75,Credit Card,2022-07-29,Mall of Istanbul

In [10]:
result_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92 entries, 8 to 99
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      92 non-null     object
 1   customer_id     92 non-null     object
 2   gender          92 non-null     object
 3   age             92 non-null     Int64
 4   category        92 non-null     object
 5   quantity        92 non-null     Int64
 6   price           92 non-null     float64
 7   payment_method  92 non-null     object
 8   invoice_date    92 non-null     dbdate
 9   shopping_mall   92 non-null     object
dtypes: Int64(2), dbdate(1), float64(1), object(6)
memory usage: 8.1+ KB

In [11]:
result_df.isna().count()

invoice_no        92
customer_id       92
gender            92
age               92
category          92
quantity          92
price             92
payment_method    92
invoice_date      92
shopping_mall     92
dtype: int64

In [12]:
result_df = result_df.drop_duplicates()

In [14]:
#Publishing data to Google Big Query
#it's also important to change the path and project you want to export your data
#so that you won't be modifying original data if something goes wrong - it will be
#irreversible.
result_df.to_gbq(
    destination_table="dataset1.customers", #here we are changing original data
    project_id="my-project-26-01-2026", #saving to the same project
    if_exists="replace", #we are deleting the previous table, we can also append
    credentials=credentials
)

/tmp/ipykernel_811/2477833773.py:5: FutureWarning: to_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.to_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.to_gbq
  result_df.to_gbq(
100%|██████████| 1/1 [00:00<00:00, 8097.11it/s]