<a href="https://colab.research.google.com/github/lisagamilton/python_tasks_logical/blob/main/pandas_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://drive.google.com/file/d/1SLLgN_zVD9Rz3w0k1FJMUphJcQ_cG5we/view?usp=sharing

https://drive.google.com/file/d/1smkce0CDQkHTdGRbhGIhzu2IcHZzYeUJ/view?usp=sharing

https://drive.google.com/file/d/1HPL30tGrmhIIhGcOUXzvp0fvpEsLCfAc/view?usp=sharing

In [1]:
! gdown --id 1SLLgN_zVD9Rz3w0k1FJMUphJcQ_cG5we

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1SLLgN_zVD9Rz3w0k1FJMUphJcQ_cG5we
To: /content/customer_shopping_data.csv
100% 6.24k/6.24k [00:00<00:00, 14.5MB/s]

In [2]:
! gdown --id 1smkce0CDQkHTdGRbhGIhzu2IcHZzYeUJ

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1smkce0CDQkHTdGRbhGIhzu2IcHZzYeUJ
To: /content/customers.csv
100% 1.84k/1.84k [00:00<00:00, 6.45MB/s]

In [3]:
! gdown --id 1HPL30tGrmhIIhGcOUXzvp0fvpEsLCfAc

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1HPL30tGrmhIIhGcOUXzvp0fvpEsLCfAc
To: /content/payment_method.csv
100% 67.0/67.0 [00:00<00:00, 243kB/s]

In [100]:
import pandas as pd
clients_q1_df = pd.DataFrame({
    'ClientID':[1,2],
    'ClientName':['Alice','Bob'],
    'Quarter':['Q1','Q1']
})

clients_q2_df = pd.DataFrame({
    'ClientID':[3,4],
    'ClientName':['Charlie','David'],
    'Quarter':['Q2','Q2']
})

concatenated_df = pd.concat([clients_q1_df,clients_q2_df],axis=0)
print(concatenated_df)

   ClientID ClientName Quarter
0         1      Alice      Q1
1         2        Bob      Q1
0         3    Charlie      Q2
1         4      David      Q2

In [101]:
sales_df = pd.DataFrame({
    'Region':['North','South','North','South','East','East'],
    'Sales':[200,150,300,350,100,250]
})

grouped_df = sales_df.groupby('Region')['Sales'].agg('mean')
grouped_df

Region
East     175.0
North    250.0
South    250.0
Name: Sales, dtype: float64

In [102]:
sales_df = pd.DataFrame({
    'Region':['North','South','North','South','East','East'],
    'Product':['A','A','B','B','A','B'],
    'Sales':[200,150,300,350,100,250]
})

pivot_df = pd.pivot_table(sales_df,values='Sales',index='Region',columns='Product',aggfunc='sum')
pivot_df

Product    A    B
Region
East     100  250
North    200  300
South    150  350

In [103]:
pivot_df = pd.pivot_table(sales_df,
                          values='Sales',
                          index='Region',
                          columns='Product',
                          aggfunc=['sum','mean','count'],
                          fill_value=0)
pivot_df

         sum        mean        count
Product    A    B      A      B     A  B
Region
East     100  250  100.0  250.0     1  1
North    200  300  200.0  300.0     1  1
South    150  350  150.0  350.0     1  1

In [104]:
customers = pd.read_csv('/content/customers.csv')

In [105]:
payment = pd.read_csv('/content/payment_method.csv')

In [106]:
shopping_data = pd.read_csv('/content/customer_shopping_data.csv')

In [107]:
customers.head(5)

  customer_id  gender  age
0     C241288  Female   28
1     C111565    Male   21
2     C266599    Male   20
3     C988172  Female   66
4     C189076  Female   53

In [108]:
payment.head(5)

   payment_type_id payment_method
0                1    Credit Card
1                2     Debit Card
2                3           Cash

In [109]:
shopping_data.head(5)

,invoice_no,customer_id,payment_method,invoice_date,category,quantity,price,shopping_mall
0,I138884,C241288,1,5/8/2022,Clothing,5,"1500,4",Kanyon
1,I317333,C111565,2,12/12/2021,Shoes,3,"1800,51",Forum Istanbul
2,I127801,C266599,3,9/11/2021,Clothing,1,"300,08",Metrocity
3,I173702,C988172,1,16/05/2021,Shoes,5,"3000,85",Metropol AVM
4,I337046,C189076,3,24/10/2021,Books,4,"60,6",Kanyon

In [110]:
merged_df = pd.merge(shopping_data,customers,on='customer_id',how='left')

In [111]:
df = pd.merge(merged_df,payment,left_on='payment_method',right_on='payment_type_id',how='left')
df

,invoice_no,customer_id,payment_method_x,invoice_date,category,quantity,price,shopping_mall,gender,age,payment_type_id,payment_method_y
0,I138884,C241288,1,5/8/2022,Clothing,5,"1500,4",Kanyon,Female,28,1,Credit Card
1,I317333,C111565,2,12/12/2021,Shoes,3,"1800,51",Forum Istanbul,Male,21,2,Debit Card
2,I127801,C266599,3,9/11/2021,Clothing,1,"300,08",Metrocity,Male,20,3,Cash
3,I173702,C988172,1,16/05/2021,Shoes,5,"3000,85",Metropol AVM,Female,66,1,Credit Card
4,I337046,C189076,3,24/10/2021,Books,4,"60,6",Kanyon,Female,53,3,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...
95,I172458,C277842,2,17/12/2021,Clothing,2,"600,16",Cevahir AVM,Female,19,2,Debit Card
96,I297270,C183011,1,31/12/2022,Clothing,5,"1500,4",Metropol AVM,Male,62,1,Credit Card
97,I153930,C567813,3,9/8/2022,Food & Beverage,3,"15,69",Forum Istanbul,Male,39,3,Cash
98,I282854,C282974,3,31/07/2022,Clothing,3,"900,24",Kanyon,Female,33,3,Cash
99,I869144,C181972,2,4/5/2021,Food & Beverage,4,"20,92",Mall of Istanbul,Female,26,2,Debit Card

In [112]:
df.drop(columns=['payment_type_id'],axis=1,inplace=True)

In [114]:
df = df.rename({'payment_method_x':'payment_method_id','payment_method_y':'payment_method'}, axis="columns")

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   invoice_no         100 non-null    object
 1   customer_id        100 non-null    object
 2   payment_method_id  100 non-null    int64
 3   invoice_date       100 non-null    object
 4   category           100 non-null    object
 5   quantity           100 non-null    int64
 6   price              100 non-null    object
 7   shopping_mall      100 non-null    object
 8   gender             100 non-null    object
 9   age                100 non-null    int64
 10  payment_method     100 non-null    object
dtypes: int64(3), object(8)
memory usage: 8.7+ KB

In [116]:
df['price'] = df['price'].replace(',','.',regex=True).astype('float')

In [117]:
df

,invoice_no,customer_id,payment_method_id,invoice_date,category,quantity,price,shopping_mall,gender,age,payment_method
0,I138884,C241288,1,5/8/2022,Clothing,5,1500.40,Kanyon,Female,28,Credit Card
1,I317333,C111565,2,12/12/2021,Shoes,3,1800.51,Forum Istanbul,Male,21,Debit Card
2,I127801,C266599,3,9/11/2021,Clothing,1,300.08,Metrocity,Male,20,Cash
3,I173702,C988172,1,16/05/2021,Shoes,5,3000.85,Metropol AVM,Female,66,Credit Card
4,I337046,C189076,3,24/10/2021,Books,4,60.60,Kanyon,Female,53,Cash
...,...,...,...,...,...,...,...,...,...,...,...
95,I172458,C277842,2,17/12/2021,Clothing,2,600.16,Cevahir AVM,Female,19,Debit Card
96,I297270,C183011,1,31/12/2022,Clothing,5,1500.40,Metropol AVM,Male,62,Credit Card
97,I153930,C567813,3,9/8/2022,Food & Beverage,3,15.69,Forum Istanbul,Male,39,Cash
98,I282854,C282974,3,31/07/2022,Clothing,3,900.24,Kanyon,Female,33,Cash
99,I869144,C181972,2,4/5/2021,Food & Beverage,4,20.92,Mall of Istanbul,Female,26,Debit Card

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   invoice_no         100 non-null    object
 1   customer_id        100 non-null    object
 2   payment_method_id  100 non-null    int64
 3   invoice_date       100 non-null    object
 4   category           100 non-null    object
 5   quantity           100 non-null    int64
 6   price              100 non-null    float64
 7   shopping_mall      100 non-null    object
 8   gender             100 non-null    object
 9   age                100 non-null    int64
 10  payment_method     100 non-null    object
dtypes: float64(1), int64(3), object(7)
memory usage: 8.7+ KB

In [119]:
df['gender'] = df['gender'].fillna('No_info')

In [120]:
# Quantity of clients based on gender
df.groupby('gender')['customer_id'].count()

gender
Female    60
Male      40
Name: customer_id, dtype: int64

In [121]:
df['total_purchase'] = df['price'] * df['quantity']

In [122]:
# Customer count and total purchase value by store and gender
df.groupby(['gender','shopping_mall'])['total_purchase'].agg(['count','sum'])

                          count       sum
gender shopping_mall
Female Cevahir AVM            4   6654.15
       Emaar Square Mall      3  16035.90
       Forum Istanbul         2   7880.75
       Istinye Park           7   2216.98
       Kanyon                17  46522.58
       Mall of Istanbul       8  29692.31
       Metrocity             10  39723.95
       Metropol AVM           3  16855.13
       Viaport Outlet         1     47.07
       Zorlu Center           5  22000.14
Male   Cevahir AVM            4   3079.65
       Emaar Square Mall      6  10674.03
       Forum Istanbul         3  20452.85
       Istinye Park           2    509.30
       Kanyon                 6  35163.52
       Mall of Istanbul       7  27771.30
       Metrocity              5   8513.24
       Metropol AVM           4  12766.00
       Viaport Outlet         1  15004.25
       Zorlu Center           2    744.69

In [123]:
# Total purchase value by payment method
df.groupby('payment_method')['total_purchase'].sum()

payment_method
Cash           137122.96
Credit Card    137639.31
Debit Card      47545.52
Name: total_purchase, dtype: float64

In [127]:
# Create pivot in which show: 1. Shopping mall 2.  Clients quantity 3.  Total purchase value 4.  Average receipt
pivot_df = pd.pivot_table(df,
                          values =['total_purchase'],
                          index='shopping_mall',
                          aggfunc=['count','sum','mean']
                          )
pivot_df

                           count            sum           mean
                  total_purchase total_purchase total_purchase
shopping_mall
Cevahir AVM                    8        9733.80    1216.725000
Emaar Square Mall              9       26709.93    2967.770000
Forum Istanbul                 5       28333.60    5666.720000
Istinye Park                   9        2726.28     302.920000
Kanyon                        23       81686.10    3551.569565
Mall of Istanbul              15       57463.61    3830.907333
Metrocity                     15       48237.19    3215.812667
Metropol AVM                   7       29621.13    4231.590000
Viaport Outlet                 2       15051.32    7525.660000
Zorlu Center                   7       22744.83    3249.261429

In [130]:
pivot_df.columns = ['count', 'sum', 'mean']

In [131]:
pivot_df

                   count       sum         mean
shopping_mall
Cevahir AVM            8   9733.80  1216.725000
Emaar Square Mall      9  26709.93  2967.770000
Forum Istanbul         5  28333.60  5666.720000
Istinye Park           9   2726.28   302.920000
Kanyon                23  81686.10  3551.569565
Mall of Istanbul      15  57463.61  3830.907333
Metrocity             15  48237.19  3215.812667
Metropol AVM           7  29621.13  4231.590000
Viaport Outlet         2  15051.32  7525.660000
Zorlu Center           7  22744.83  3249.261429

In [134]:
pivot_df.to_csv('pivot_df.csv', index=True)